version: '3.3'
services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    env_file:
      - ./.env

  frontend:
    image: mikhailkushnerev/foodgram-frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"

  backend:
    image: mikhailkushnerev/foodgram:v1.0.1
    restart: always
    volumes:
      # - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      # - ../data/:/var/html/data/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      # - data_value:/var/html/data/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  # data_value:
  static_value:
  media_value: