version: '20.10.14'
services:
  db:
    container_name: pg_db
    image: postgres:14.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../.env
      
  pg_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mikhail@yandex.com
      - PGADMIN_DEFAULT_PASSWORD=mikhail-food
    ports:
      - "5050:80"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ../.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
