# Generated by Django 4.0.4 on 2022-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='Вы уже добавляли этот рецепт в избранное!',
        ),
    ]
