# Generated by Django 4.0.4 on 2022-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountofingrediend',
            name='Использовать один ингредиент более 1-го раза нельзя!',
        ),
    ]
