# Generated by Django 4.0.4 on 2022-05-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_amountofingrediend_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
    ]
