# Generated by Django 4.0.4 on 2022-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_amountofingrediend_использовать один ингредиент более 1-го раза нельзя!'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amountofingrediend',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='Использовать один ингредиент более 1-го раза нельзя!'),
        ),
    ]
