# Generated by Django 4.0.4 on 2022-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_unique_name_author'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_name_recipe',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
