# Generated by Django 4.0.4 on 2022-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_amountofingrediend_использовать один ингредиент более 1-го раза нельзя!'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#E26C2D', 'Оранжевый'), ('#49B64E', 'Зеленый'), ('#8775D2', 'Синий')], max_length=16, unique=True),
        ),
    ]
