# Generated by Django 4.0.4 on 2022-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_favourite_unique_name_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_name_author',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Рецепт уже находится в избранном!'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='Такой рецепт уже создавался Вами!'),
        ),
    ]
