# Generated by Django 4.0.4 on 2022-05-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_favourite_unique_user_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='Такой рецепт уже создавался Вами!',
        ),
    ]
