# Generated by Django 4.0.4 on 2022-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_такой рецепт уже создавался вами!'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='Такой рецепт уже создавался Вами!'),
        ),
    ]
